spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: CHANGEME
    password: CHANGEME
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  from: <mailto:test@mailtrap.io>
